# Generated by Django 3.1.1 on 2020-10-02 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mic', '0002_auto_20201002_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='is_fav',
        ),
    ]
